"""empty message

Revision ID: 84a1337bf5e1
Revises: adb00f3d86c6
Create Date: 2026-06-24 20:47:45.699176

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '84a1337bf5e1'
down_revision: Union[str, None] = 'adb00f3d86c6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_awards_unique_id'), 'awards', ['unique_id'], unique=False)
    op.create_index(op.f('ix_blacklisted_tokens_unique_id'), 'blacklisted_tokens', ['unique_id'], unique=False)
    op.create_index(op.f('ix_blogs_unique_id'), 'blogs', ['unique_id'], unique=False)
    op.create_index(op.f('ix_categories_unique_id'), 'categories', ['unique_id'], unique=False)
    op.create_index(op.f('ix_category_association_unique_id'), 'category_association', ['unique_id'], unique=False)
    op.create_index(op.f('ix_certifications_unique_id'), 'certifications', ['unique_id'], unique=False)
    op.create_index(op.f('ix_education_unique_id'), 'education', ['unique_id'], unique=False)
    op.create_index(op.f('ix_experiences_unique_id'), 'experiences', ['unique_id'], unique=False)
    op.create_index(op.f('ix_files_unique_id'), 'files', ['unique_id'], unique=False)
    op.create_index(op.f('ix_messages_unique_id'), 'messages', ['unique_id'], unique=False)
    op.create_index(op.f('ix_profile_unique_id'), 'profile', ['unique_id'], unique=False)
    op.create_index(op.f('ix_projects_unique_id'), 'projects', ['unique_id'], unique=False)
    op.create_index(op.f('ix_services_unique_id'), 'services', ['unique_id'], unique=False)
    op.create_index(op.f('ix_skills_unique_id'), 'skills', ['unique_id'], unique=False)
    op.create_index(op.f('ix_tag_association_unique_id'), 'tag_association', ['unique_id'], unique=False)
    op.create_index(op.f('ix_tags_unique_id'), 'tags', ['unique_id'], unique=False)
    op.create_index(op.f('ix_testimonials_unique_id'), 'testimonials', ['unique_id'], unique=False)
    op.create_index(op.f('ix_tokens_unique_id'), 'tokens', ['unique_id'], unique=False)
    op.create_index(op.f('ix_users_unique_id'), 'users', ['unique_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_unique_id'), table_name='users')
    op.drop_index(op.f('ix_tokens_unique_id'), table_name='tokens')
    op.drop_index(op.f('ix_testimonials_unique_id'), table_name='testimonials')
    op.drop_index(op.f('ix_tags_unique_id'), table_name='tags')
    op.drop_index(op.f('ix_tag_association_unique_id'), table_name='tag_association')
    op.drop_index(op.f('ix_skills_unique_id'), table_name='skills')
    op.drop_index(op.f('ix_services_unique_id'), table_name='services')
    op.drop_index(op.f('ix_projects_unique_id'), table_name='projects')
    op.drop_index(op.f('ix_profile_unique_id'), table_name='profile')
    op.drop_index(op.f('ix_messages_unique_id'), table_name='messages')
    op.drop_index(op.f('ix_files_unique_id'), table_name='files')
    op.drop_index(op.f('ix_experiences_unique_id'), table_name='experiences')
    op.drop_index(op.f('ix_education_unique_id'), table_name='education')
    op.drop_index(op.f('ix_certifications_unique_id'), table_name='certifications')
    op.drop_index(op.f('ix_category_association_unique_id'), table_name='category_association')
    op.drop_index(op.f('ix_categories_unique_id'), table_name='categories')
    op.drop_index(op.f('ix_blogs_unique_id'), table_name='blogs')
    op.drop_index(op.f('ix_blacklisted_tokens_unique_id'), table_name='blacklisted_tokens')
    op.drop_index(op.f('ix_awards_unique_id'), table_name='awards')
    # ### end Alembic commands ###
