"""add new columns to projects table

Revision ID: 9fea68b4fa22
Revises: f02651243476
Create Date: 2025-07-26 12:59:31.232304

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9fea68b4fa22'
down_revision: Union[str, None] = 'f02651243476'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('features', sa.JSON(), nullable=True))
    op.add_column('projects', sa.Column('challenges_and_solutions', sa.JSON(), nullable=True))
    op.add_column('projects', sa.Column('results', sa.JSON(), nullable=True))
    op.add_column('projects', sa.Column('technical_details', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projects', 'technical_details')
    op.drop_column('projects', 'results')
    op.drop_column('projects', 'challenges_and_solutions')
    op.drop_column('projects', 'features')
    # ### end Alembic commands ###
