"""update project table

Revision ID: bf441e838d68
Revises: 9fea68b4fa22
Create Date: 2025-07-27 19:12:22.800648

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bf441e838d68'
down_revision: Union[str, None] = '9fea68b4fa22'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('sector', sa.String(), nullable=True))
    op.add_column('projects', sa.Column('start_date', sa.DateTime(), nullable=True))
    op.add_column('projects', sa.Column('end_date', sa.DateTime(), nullable=True))
    op.add_column('projects', sa.Column('status', sa.String(), nullable=True))
    op.create_index(op.f('ix_projects_domain'), 'projects', ['domain'], unique=False)
    op.create_index(op.f('ix_projects_project_type'), 'projects', ['project_type'], unique=False)
    op.create_index(op.f('ix_projects_role'), 'projects', ['role'], unique=False)
    op.create_index(op.f('ix_projects_sector'), 'projects', ['sector'], unique=False)
    op.create_index(op.f('ix_projects_status'), 'projects', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_projects_status'), table_name='projects')
    op.drop_index(op.f('ix_projects_sector'), table_name='projects')
    op.drop_index(op.f('ix_projects_role'), table_name='projects')
    op.drop_index(op.f('ix_projects_project_type'), table_name='projects')
    op.drop_index(op.f('ix_projects_domain'), table_name='projects')
    op.drop_column('projects', 'status')
    op.drop_column('projects', 'end_date')
    op.drop_column('projects', 'start_date')
    op.drop_column('projects', 'sector')
    # ### end Alembic commands ###
