"""add description to education and experience tables

Revision ID: f02651243476
Revises: 
Create Date: 2025-07-24 23:57:17.459639

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f02651243476'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('education', sa.Column('description', sa.Text(), nullable=True))
    op.add_column('experiences', sa.Column('description', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('experiences', 'description')
    op.drop_column('education', 'description')
    # ### end Alembic commands ###
